### ISSUE TITLE
Option to define the words in a file

### ISSUE THREAD

**Issue by aleixmorgadas** [dgarcia360/excludedwords-lint#1]
As a user, I might want to add the words into a file. Or even have a default list :smile:

**Comment by dgarcia360** [comment]
@aleixmorgadas thanks for the feedback!

Now you can import the words from a file using --config option. Here you have as well a [starting default list](https://gist.github.com/dgarcia360/f89b0d591882aabb7b8b07c71ae4aad1). 

Update + docs will be updated soon (note that "soon" without context is also a lazy word)  😀

**Comment by aleixmorgadas** [comment]
Thanks @dgarcia360 to implement the `--config option`. I do think this kind of tool can improve the CI process with documentation. Still a lot to do to improve how we document projects in a non-tedious way, this tool is a step forward ^^
